(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type tupleoperation = [
| `TUPLE_OPERATION_WRITE [@printer fun fmt _ -> Format.pp_print_string fmt "TUPLE_OPERATION_WRITE"] [@name "TUPLE_OPERATION_WRITE"]
| `TUPLE_OPERATION_DELETE [@printer fun fmt _ -> Format.pp_print_string fmt "TUPLE_OPERATION_DELETE"] [@name "TUPLE_OPERATION_DELETE"]
] [@@deriving yojson, show { with_path = false }, eq];;

let tupleoperation_of_yojson json = tupleoperation_of_yojson (`List [json])
let tupleoperation_to_yojson e =
    match tupleoperation_to_yojson e with
    | `List [json] -> json
    | json -> json

type typename = [
| `TYPE_NAME_UNSPECIFIED [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_UNSPECIFIED"] [@name "TYPE_NAME_UNSPECIFIED"]
| `TYPE_NAME_ANY [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_ANY"] [@name "TYPE_NAME_ANY"]
| `TYPE_NAME_BOOL [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_BOOL"] [@name "TYPE_NAME_BOOL"]
| `TYPE_NAME_STRING [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_STRING"] [@name "TYPE_NAME_STRING"]
| `TYPE_NAME_INT [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_INT"] [@name "TYPE_NAME_INT"]
| `TYPE_NAME_UINT [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_UINT"] [@name "TYPE_NAME_UINT"]
| `TYPE_NAME_DOUBLE [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_DOUBLE"] [@name "TYPE_NAME_DOUBLE"]
| `TYPE_NAME_DURATION [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_DURATION"] [@name "TYPE_NAME_DURATION"]
| `TYPE_NAME_TIMESTAMP [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_TIMESTAMP"] [@name "TYPE_NAME_TIMESTAMP"]
| `TYPE_NAME_MAP [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_MAP"] [@name "TYPE_NAME_MAP"]
| `TYPE_NAME_LIST [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_LIST"] [@name "TYPE_NAME_LIST"]
| `TYPE_NAME_IPADDRESS [@printer fun fmt _ -> Format.pp_print_string fmt "TYPE_NAME_IPADDRESS"] [@name "TYPE_NAME_IPADDRESS"]
] [@@deriving yojson, show { with_path = false }, eq];;

let typename_of_yojson json = typename_of_yojson (`List [json])
let typename_to_yojson e =
    match typename_to_yojson e with
    | `List [json] -> json
    | json -> json

type autherrorcode = [
| `No_auth_error [@printer fun fmt _ -> Format.pp_print_string fmt "no_auth_error"] [@name "no_auth_error"]
| `Auth_failed_invalid_subject [@printer fun fmt _ -> Format.pp_print_string fmt "auth_failed_invalid_subject"] [@name "auth_failed_invalid_subject"]
| `Auth_failed_invalid_audience [@printer fun fmt _ -> Format.pp_print_string fmt "auth_failed_invalid_audience"] [@name "auth_failed_invalid_audience"]
| `Auth_failed_invalid_issuer [@printer fun fmt _ -> Format.pp_print_string fmt "auth_failed_invalid_issuer"] [@name "auth_failed_invalid_issuer"]
| `Invalid_claims [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_claims"] [@name "invalid_claims"]
| `Auth_failed_invalid_bearer_token [@printer fun fmt _ -> Format.pp_print_string fmt "auth_failed_invalid_bearer_token"] [@name "auth_failed_invalid_bearer_token"]
| `Bearer_token_missing [@printer fun fmt _ -> Format.pp_print_string fmt "bearer_token_missing"] [@name "bearer_token_missing"]
| `Unauthenticated [@printer fun fmt _ -> Format.pp_print_string fmt "unauthenticated"] [@name "unauthenticated"]
| `Forbidden [@printer fun fmt _ -> Format.pp_print_string fmt "forbidden"] [@name "forbidden"]
] [@@deriving yojson, show { with_path = false }, eq];;

let autherrorcode_of_yojson json = autherrorcode_of_yojson (`List [json])
let autherrorcode_to_yojson e =
    match autherrorcode_to_yojson e with
    | `List [json] -> json
    | json -> json

type internalerrorcode = [
| `No_internal_error [@printer fun fmt _ -> Format.pp_print_string fmt "no_internal_error"] [@name "no_internal_error"]
| `Internal_error [@printer fun fmt _ -> Format.pp_print_string fmt "internal_error"] [@name "internal_error"]
| `Deadline_exceeded [@printer fun fmt _ -> Format.pp_print_string fmt "deadline_exceeded"] [@name "deadline_exceeded"]
| `Already_exists [@printer fun fmt _ -> Format.pp_print_string fmt "already_exists"] [@name "already_exists"]
| `Resource_exhausted [@printer fun fmt _ -> Format.pp_print_string fmt "resource_exhausted"] [@name "resource_exhausted"]
| `Failed_precondition [@printer fun fmt _ -> Format.pp_print_string fmt "failed_precondition"] [@name "failed_precondition"]
| `Aborted [@printer fun fmt _ -> Format.pp_print_string fmt "aborted"] [@name "aborted"]
| `Out_of_range [@printer fun fmt _ -> Format.pp_print_string fmt "out_of_range"] [@name "out_of_range"]
| `Unavailable [@printer fun fmt _ -> Format.pp_print_string fmt "unavailable"] [@name "unavailable"]
| `Data_loss [@printer fun fmt _ -> Format.pp_print_string fmt "data_loss"] [@name "data_loss"]
] [@@deriving yojson, show { with_path = false }, eq];;

let internalerrorcode_of_yojson json = internalerrorcode_of_yojson (`List [json])
let internalerrorcode_to_yojson e =
    match internalerrorcode_to_yojson e with
    | `List [json] -> json
    | json -> json

type on_missing = [
| `Error [@printer fun fmt _ -> Format.pp_print_string fmt "error"] [@name "error"]
| `Ignore [@printer fun fmt _ -> Format.pp_print_string fmt "ignore"] [@name "ignore"]
] [@@deriving yojson, show { with_path = false }, eq];;

let on_missing_of_yojson json = on_missing_of_yojson (`List [json])
let on_missing_to_yojson e =
    match on_missing_to_yojson e with
    | `List [json] -> json
    | json -> json

type errorcode = [
| `No_error [@printer fun fmt _ -> Format.pp_print_string fmt "no_error"] [@name "no_error"]
| `Validation_error [@printer fun fmt _ -> Format.pp_print_string fmt "validation_error"] [@name "validation_error"]
| `Authorization_model_not_found [@printer fun fmt _ -> Format.pp_print_string fmt "authorization_model_not_found"] [@name "authorization_model_not_found"]
| `Authorization_model_resolution_too_complex [@printer fun fmt _ -> Format.pp_print_string fmt "authorization_model_resolution_too_complex"] [@name "authorization_model_resolution_too_complex"]
| `Invalid_write_input [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_write_input"] [@name "invalid_write_input"]
| `Cannot_allow_duplicate_tuples_in_one_request [@printer fun fmt _ -> Format.pp_print_string fmt "cannot_allow_duplicate_tuples_in_one_request"] [@name "cannot_allow_duplicate_tuples_in_one_request"]
| `Cannot_allow_duplicate_types_in_one_request [@printer fun fmt _ -> Format.pp_print_string fmt "cannot_allow_duplicate_types_in_one_request"] [@name "cannot_allow_duplicate_types_in_one_request"]
| `Cannot_allow_multiple_references_to_one_relation [@printer fun fmt _ -> Format.pp_print_string fmt "cannot_allow_multiple_references_to_one_relation"] [@name "cannot_allow_multiple_references_to_one_relation"]
| `Invalid_continuation_token [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_continuation_token"] [@name "invalid_continuation_token"]
| `Invalid_tuple_set [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_tuple_set"] [@name "invalid_tuple_set"]
| `Invalid_check_input [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_check_input"] [@name "invalid_check_input"]
| `Invalid_expand_input [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_expand_input"] [@name "invalid_expand_input"]
| `Unsupported_user_set [@printer fun fmt _ -> Format.pp_print_string fmt "unsupported_user_set"] [@name "unsupported_user_set"]
| `Invalid_object_format [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_object_format"] [@name "invalid_object_format"]
| `Write_failed_due_to_invalid_input [@printer fun fmt _ -> Format.pp_print_string fmt "write_failed_due_to_invalid_input"] [@name "write_failed_due_to_invalid_input"]
| `Authorization_model_assertions_not_found [@printer fun fmt _ -> Format.pp_print_string fmt "authorization_model_assertions_not_found"] [@name "authorization_model_assertions_not_found"]
| `Latest_authorization_model_not_found [@printer fun fmt _ -> Format.pp_print_string fmt "latest_authorization_model_not_found"] [@name "latest_authorization_model_not_found"]
| `Type_not_found [@printer fun fmt _ -> Format.pp_print_string fmt "type_not_found"] [@name "type_not_found"]
| `Relation_not_found [@printer fun fmt _ -> Format.pp_print_string fmt "relation_not_found"] [@name "relation_not_found"]
| `Empty_relation_definition [@printer fun fmt _ -> Format.pp_print_string fmt "empty_relation_definition"] [@name "empty_relation_definition"]
| `Invalid_user [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_user"] [@name "invalid_user"]
| `Invalid_tuple [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_tuple"] [@name "invalid_tuple"]
| `Unknown_relation [@printer fun fmt _ -> Format.pp_print_string fmt "unknown_relation"] [@name "unknown_relation"]
| `Store_id_invalid_length [@printer fun fmt _ -> Format.pp_print_string fmt "store_id_invalid_length"] [@name "store_id_invalid_length"]
| `Assertions_too_many_items [@printer fun fmt _ -> Format.pp_print_string fmt "assertions_too_many_items"] [@name "assertions_too_many_items"]
| `Id_too_long [@printer fun fmt _ -> Format.pp_print_string fmt "id_too_long"] [@name "id_too_long"]
| `Authorization_model_id_too_long [@printer fun fmt _ -> Format.pp_print_string fmt "authorization_model_id_too_long"] [@name "authorization_model_id_too_long"]
| `Tuple_key_value_not_specified [@printer fun fmt _ -> Format.pp_print_string fmt "tuple_key_value_not_specified"] [@name "tuple_key_value_not_specified"]
| `Tuple_keys_too_many_or_too_few_items [@printer fun fmt _ -> Format.pp_print_string fmt "tuple_keys_too_many_or_too_few_items"] [@name "tuple_keys_too_many_or_too_few_items"]
| `Page_size_invalid [@printer fun fmt _ -> Format.pp_print_string fmt "page_size_invalid"] [@name "page_size_invalid"]
| `Param_missing_value [@printer fun fmt _ -> Format.pp_print_string fmt "param_missing_value"] [@name "param_missing_value"]
| `Difference_base_missing_value [@printer fun fmt _ -> Format.pp_print_string fmt "difference_base_missing_value"] [@name "difference_base_missing_value"]
| `Subtract_base_missing_value [@printer fun fmt _ -> Format.pp_print_string fmt "subtract_base_missing_value"] [@name "subtract_base_missing_value"]
| `Object_too_long [@printer fun fmt _ -> Format.pp_print_string fmt "object_too_long"] [@name "object_too_long"]
| `Relation_too_long [@printer fun fmt _ -> Format.pp_print_string fmt "relation_too_long"] [@name "relation_too_long"]
| `Type_definitions_too_few_items [@printer fun fmt _ -> Format.pp_print_string fmt "type_definitions_too_few_items"] [@name "type_definitions_too_few_items"]
| `Type_invalid_length [@printer fun fmt _ -> Format.pp_print_string fmt "type_invalid_length"] [@name "type_invalid_length"]
| `Type_invalid_pattern [@printer fun fmt _ -> Format.pp_print_string fmt "type_invalid_pattern"] [@name "type_invalid_pattern"]
| `Relations_too_few_items [@printer fun fmt _ -> Format.pp_print_string fmt "relations_too_few_items"] [@name "relations_too_few_items"]
| `Relations_too_long [@printer fun fmt _ -> Format.pp_print_string fmt "relations_too_long"] [@name "relations_too_long"]
| `Relations_invalid_pattern [@printer fun fmt _ -> Format.pp_print_string fmt "relations_invalid_pattern"] [@name "relations_invalid_pattern"]
| `Object_invalid_pattern [@printer fun fmt _ -> Format.pp_print_string fmt "object_invalid_pattern"] [@name "object_invalid_pattern"]
| `Query_string_type_continuation_token_mismatch [@printer fun fmt _ -> Format.pp_print_string fmt "query_string_type_continuation_token_mismatch"] [@name "query_string_type_continuation_token_mismatch"]
| `Exceeded_entity_limit [@printer fun fmt _ -> Format.pp_print_string fmt "exceeded_entity_limit"] [@name "exceeded_entity_limit"]
| `Invalid_contextual_tuple [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_contextual_tuple"] [@name "invalid_contextual_tuple"]
| `Duplicate_contextual_tuple [@printer fun fmt _ -> Format.pp_print_string fmt "duplicate_contextual_tuple"] [@name "duplicate_contextual_tuple"]
| `Invalid_authorization_model [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_authorization_model"] [@name "invalid_authorization_model"]
| `Unsupported_schema_version [@printer fun fmt _ -> Format.pp_print_string fmt "unsupported_schema_version"] [@name "unsupported_schema_version"]
| `Cancelled [@printer fun fmt _ -> Format.pp_print_string fmt "cancelled"] [@name "cancelled"]
| `Invalid_start_time [@printer fun fmt _ -> Format.pp_print_string fmt "invalid_start_time"] [@name "invalid_start_time"]
] [@@deriving yojson, show { with_path = false }, eq];;

let errorcode_of_yojson json = errorcode_of_yojson (`List [json])
let errorcode_to_yojson e =
    match errorcode_to_yojson e with
    | `List [json] -> json
    | json -> json

type unprocessablecontenterrorcode = [
| `No_throttled_error_code [@printer fun fmt _ -> Format.pp_print_string fmt "no_throttled_error_code"] [@name "no_throttled_error_code"]
| `Throttled_timeout_error [@printer fun fmt _ -> Format.pp_print_string fmt "throttled_timeout_error"] [@name "throttled_timeout_error"]
] [@@deriving yojson, show { with_path = false }, eq];;

let unprocessablecontenterrorcode_of_yojson json = unprocessablecontenterrorcode_of_yojson (`List [json])
let unprocessablecontenterrorcode_to_yojson e =
    match unprocessablecontenterrorcode_to_yojson e with
    | `List [json] -> json
    | json -> json

type consistencypreference = [
| `UNSPECIFIED [@printer fun fmt _ -> Format.pp_print_string fmt "UNSPECIFIED"] [@name "UNSPECIFIED"]
| `MINIMIZE_LATENCY [@printer fun fmt _ -> Format.pp_print_string fmt "MINIMIZE_LATENCY"] [@name "MINIMIZE_LATENCY"]
| `HIGHER_CONSISTENCY [@printer fun fmt _ -> Format.pp_print_string fmt "HIGHER_CONSISTENCY"] [@name "HIGHER_CONSISTENCY"]
] [@@deriving yojson, show { with_path = false }, eq];;

let consistencypreference_of_yojson json = consistencypreference_of_yojson (`List [json])
let consistencypreference_to_yojson e =
    match consistencypreference_to_yojson e with
    | `List [json] -> json
    | json -> json

type nullvalue = [
| `NULL_VALUE [@printer fun fmt _ -> Format.pp_print_string fmt "NULL_VALUE"] [@name "NULL_VALUE"]
] [@@deriving yojson, show { with_path = false }, eq];;

let nullvalue_of_yojson json = nullvalue_of_yojson (`List [json])
let nullvalue_to_yojson e =
    match nullvalue_to_yojson e with
    | `List [json] -> json
    | json -> json

type notfounderrorcode = [
| `No_not_found_error [@printer fun fmt _ -> Format.pp_print_string fmt "no_not_found_error"] [@name "no_not_found_error"]
| `Undefined_endpoint [@printer fun fmt _ -> Format.pp_print_string fmt "undefined_endpoint"] [@name "undefined_endpoint"]
| `Store_id_not_found [@printer fun fmt _ -> Format.pp_print_string fmt "store_id_not_found"] [@name "store_id_not_found"]
| `Unimplemented [@printer fun fmt _ -> Format.pp_print_string fmt "unimplemented"] [@name "unimplemented"]
] [@@deriving yojson, show { with_path = false }, eq];;

let notfounderrorcode_of_yojson json = notfounderrorcode_of_yojson (`List [json])
let notfounderrorcode_to_yojson e =
    match notfounderrorcode_to_yojson e with
    | `List [json] -> json
    | json -> json
