(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val batch_check : store_id:string -> body:Batch_check_request.t -> Batch_check_response.t Lwt.t
val check : store_id:string -> body:Check_request.t -> Check_response.t Lwt.t
val create_store : body:Create_store_request.t -> Create_store_response.t Lwt.t
val delete_store : store_id:string -> unit Lwt.t
val expand : store_id:string -> body:Expand_request.t -> Expand_response.t Lwt.t
val get_store : store_id:string -> Get_store_response.t Lwt.t
val list_objects : store_id:string -> body:List_objects_request.t -> List_objects_response.t Lwt.t
val list_stores : ?page_size:int32 -> ?continuation_token:string -> ?name:string -> unit -> List_stores_response.t Lwt.t
val list_users : store_id:string -> body:List_users_request.t -> List_users_response.t Lwt.t
val read : store_id:string -> body:Read_request.t -> Read_response.t Lwt.t
val read_assertions : store_id:string -> authorization_model_id:string -> Read_assertions_response.t Lwt.t
val read_authorization_model : store_id:string -> id:string -> Read_authorization_model_response.t Lwt.t
val read_authorization_models : store_id:string -> ?page_size:int32 -> ?continuation_token:string -> unit -> Read_authorization_models_response.t Lwt.t
val read_changes : store_id:string -> ?_type:string -> ?page_size:int32 -> ?continuation_token:string -> ?start_time:string -> unit -> Read_changes_response.t Lwt.t
val write : store_id:string -> body:Write_request.t -> Yojson.Safe.t Lwt.t
val write_assertions : store_id:string -> authorization_model_id:string -> body:Write_assertions_request.t -> unit Lwt.t
val write_authorization_model : store_id:string -> body:Write_authorization_model_request.t -> Write_authorization_model_response.t Lwt.t
