(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let batch_check ~store_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/batch-check" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                Batch_check_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Batch_check_response.of_yojson) resp body

let check ~store_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/check" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                Check_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Check_response.of_yojson) resp body

let create_store ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores" in
    let headers = Request.default_headers in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                Create_store_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Create_store_response.of_yojson) resp body

let delete_store ~store_id =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers >>= fun (resp, body) ->
    Request.handle_unit_response resp

let expand ~store_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/expand" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                Expand_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Expand_response.of_yojson) resp body

let get_store ~store_id =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Get_store_response.of_yojson) resp body

let list_objects ~store_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/list-objects" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                List_objects_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap List_objects_response.of_yojson) resp body

let list_stores ?page_size ?continuation_token ?name () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores" in
    let headers = Request.default_headers in
    let uri = Request.maybe_add_query_param uri "page_size"     
    Int32.to_string
    
    
    
    
    
    
    
    
    
    
        
        
 page_size in
    let uri = Request.maybe_add_query_param uri "continuation_token"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 continuation_token in
    let uri = Request.maybe_add_query_param uri "name"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 name in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap List_stores_response.of_yojson) resp body

let list_users ~store_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/list-users" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                List_users_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap List_users_response.of_yojson) resp body

let read ~store_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/read" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                Read_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Read_response.of_yojson) resp body

let read_assertions ~store_id ~authorization_model_id =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/assertions/{authorization_model_id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let uri = Request.replace_path_param uri "authorization_model_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 authorization_model_id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Read_assertions_response.of_yojson) resp body

let read_authorization_model ~store_id ~id =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/authorization-models/{id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let uri = Request.replace_path_param uri "id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 id in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Read_authorization_model_response.of_yojson) resp body

let read_authorization_models ~store_id ?page_size ?continuation_token () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/authorization-models" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let uri = Request.maybe_add_query_param uri "page_size"     
    Int32.to_string
    
    
    
    
    
    
    
    
    
    
        
        
 page_size in
    let uri = Request.maybe_add_query_param uri "continuation_token"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 continuation_token in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Read_authorization_models_response.of_yojson) resp body

let read_changes ~store_id ?_type ?page_size ?continuation_token ?start_time () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/changes" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let uri = Request.maybe_add_query_param uri "type"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 _type in
    let uri = Request.maybe_add_query_param uri "page_size"     
    Int32.to_string
    
    
    
    
    
    
    
    
    
    
        
        
 page_size in
    let uri = Request.maybe_add_query_param uri "continuation_token"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 continuation_token in
    let uri = Request.maybe_add_query_param uri "start_time"     
    
    
    
    
    
    
    
    (fun x -> x)
    
    
    
        
        
 start_time in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Read_changes_response.of_yojson) resp body

let write ~store_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/write" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                Write_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body  resp body

let write_assertions ~store_id ~authorization_model_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/assertions/{authorization_model_id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let uri = Request.replace_path_param uri "authorization_model_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 authorization_model_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                Write_assertions_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `PUT uri ~headers ~body >>= fun (resp, body) ->
    Request.handle_unit_response resp

let write_authorization_model ~store_id ~body =
    let open Lwt.Infix in
    let uri = Request.build_uri "/stores/{store_id}/authorization-models" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "store_id"     
    
    
    
    
    
    
    
    
    (fun x -> x)
    
    
        
        
 store_id in
    let body = Request.
        
        write_as_json_body     
    
    
    
    
    
    
                Write_authorization_model_request.to_yojson
    
    
    
 body
    in
    Cohttp_lwt_unix.Client.call `POST uri ~headers ~body >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Write_authorization_model_response.of_yojson) resp body

