(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      _type: string
          
           option [@default None]
        
        
        ; [@key "@type"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    _type = None;
}

    

