(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      _object: string
          
          
        
        
        ; [@key "object"]
      relation: string
          
          
        
        
        ; [@key "relation"]
      user: string
          
          
        
        
        ; [@key "user"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (_object : string) (relation : string) (user : string) : t = {
    _object = _object;
    relation = relation;
    user = user;
}

    

