(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_key: Assertion_tuple_key.t
          
          
        
        
        ; [@key "tuple_key"]
      expectation: bool
          
          
        
        
        ; [@key "expectation"]
      contextual_tuples: Tuple_key.t list
         [@default []]
        
        ; [@key "contextual_tuples"]
      context: Yojson.Safe.t
          
           option [@default None]
        
        
        ; [@key "context"]
    (** Additional request context that will be used to evaluate any ABAC conditions encountered in the query evaluation. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuple_key : Assertion_tuple_key.t) (expectation : bool) : t = {
    tuple_key = tuple_key;
    expectation = expectation;
    contextual_tuples = [];
    context = None;
}

    

