(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      checks: Batch_check_item.t list
        
        
        ; [@key "checks"]
      authorization_model_id: string
          
           option [@default None]
        
        
        ; [@key "authorization_model_id"]
      consistency: Enums.consistencypreference
          
           option [@default None]
        
        
        ; [@key "consistency"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (checks : Batch_check_item.t list) : t = {
    checks = checks;
    authorization_model_id = None;
    consistency = None;
}

    

