(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_key: Check_request_tuple_key.t
          
          
        
        
        ; [@key "tuple_key"]
      contextual_tuples: Contextual_tuple_keys.t
          
           option [@default None]
        
        
        ; [@key "contextual_tuples"]
      context: Yojson.Safe.t
          
           option [@default None]
        
        
        ; [@key "context"]
      correlation_id: string
          
          
        
        
        ; [@key "correlation_id"]
    (** correlation_id must be a string containing only letters, numbers, or hyphens, with length ≤ 36 characters. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuple_key : Check_request_tuple_key.t) (correlation_id : string) : t = {
    tuple_key = tuple_key;
    contextual_tuples = None;
    context = None;
    correlation_id = correlation_id;
}

    

