(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      _result: (string * Batch_check_single_result.t) list
        
         [@default []] [@to_yojson JsonSupport.of_map_of [%to_yojson: Batch_check_single_result.t]] [@of_yojson JsonSupport.to_map_of [%of_yojson: Batch_check_single_result.t]]
        ; [@key "result"]
    (** map keys are the correlation_id values from the BatchCheckItems in the request *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    _result = [];
}

    

