(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      allowed: bool
          
           option [@default None]
        
        
        ; [@key "allowed"]
      resolution: string
          
           option [@default None]
        
        
        ; [@key "resolution"]
    (** For internal use only. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    allowed = None;
    resolution = None;
}

    

