(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      input_error: Enums.errorcode
          
           option [@default None]
        
        
        ; [@key "input_error"]
      internal_error: Enums.internalerrorcode
          
           option [@default None]
        
        
        ; [@key "internal_error"]
      message: string
          
           option [@default None]
        
        
        ; [@key "message"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    input_error = None;
    internal_error = None;
    message = None;
}

    

