(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_key: Check_request_tuple_key.t
          
          
        
        
        ; [@key "tuple_key"]
      contextual_tuples: Contextual_tuple_keys.t
          
           option [@default None]
        
        
        ; [@key "contextual_tuples"]
      authorization_model_id: string
          
           option [@default None]
        
        
        ; [@key "authorization_model_id"]
      trace: bool
          
           option [@default None]
        
        
        ; [@key "trace"]
    (** Defaults to false. Making it true has performance implications. *)
      context: Yojson.Safe.t
          
           option [@default None]
        
        
        ; [@key "context"]
    (** Additional request context that will be used to evaluate any ABAC conditions encountered in the query evaluation. *)
      consistency: Enums.consistencypreference
          
           option [@default None]
        
        
        ; [@key "consistency"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuple_key : Check_request_tuple_key.t) : t = {
    tuple_key = tuple_key;
    contextual_tuples = None;
    authorization_model_id = None;
    trace = None;
    context = None;
    consistency = None;
}

    

