(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      userset: string
          
          
        
        
        ; [@key "userset"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (userset : string) : t = {
    userset = userset;
}

    

