(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      type_name: Enums.typename
          
          
        
        
        ; [@key "type_name"]
      generic_types: Condition_param_type_ref.t list
         [@default []]
        
        ; [@key "generic_types"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (type_name : Enums.typename) : t = {
    type_name = type_name;
    generic_types = [];
}

    

