(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      _module: string
          
           option [@default None]
        
        
        ; [@key "module"]
      source_info: Source_info.t
          
           option [@default None]
        
        
        ; [@key "source_info"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    _module = None;
    source_info = None;
}

    

