(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      name: string
          
          
        
        
        ; [@key "name"]
      expression: string
          
          
        
        
        ; [@key "expression"]
    (** A Google CEL expression, expressed as a string. *)
      parameters: (string * Condition_param_type_ref.t) list
        
         [@default []] [@to_yojson JsonSupport.of_map_of [%to_yojson: Condition_param_type_ref.t]] [@of_yojson JsonSupport.to_map_of [%of_yojson: Condition_param_type_ref.t]]
        ; [@key "parameters"]
    (** A map of parameter names to the parameter's defined type reference. *)
      metadata: Condition_metadata.t
          
           option [@default None]
        
        
        ; [@key "metadata"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (name : string) (expression : string) : t = {
    name = name;
    expression = expression;
    parameters = [];
    metadata = None;
}

    

