(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_keys: Tuple_key.t list
        
        
        ; [@key "tuple_keys"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuple_keys : Tuple_key.t list) : t = {
    tuple_keys = tuple_keys;
}

    

