(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      id: string
          
          
        
        
        ; [@key "id"]
      name: string
          
          
        
        
        ; [@key "name"]
      created_at: string
          
          
        
        
        ; [@key "created_at"]
      updated_at: string
          
          
        
        
        ; [@key "updated_at"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (id : string) (name : string) (created_at : string) (updated_at : string) : t = {
    id = id;
    name = name;
    created_at = created_at;
    updated_at = updated_at;
}

    

