(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      base: Userset.t
          
          
        
        
        ; [@key "base"]
      subtract: Userset.t
          
          
        
        
        ; [@key "subtract"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (base : Userset.t) (subtract : Userset.t) : t = {
    base = base;
    subtract = subtract;
}

    

