(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      relation: string
          
          
        
        
        ; [@key "relation"]
      _object: string
          
          
        
        
        ; [@key "object"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (relation : string) (_object : string) : t = {
    relation = relation;
    _object = _object;
}

    

