(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_key: Expand_request_tuple_key.t
          
          
        
        
        ; [@key "tuple_key"]
      authorization_model_id: string
          
           option [@default None]
        
        
        ; [@key "authorization_model_id"]
      consistency: Enums.consistencypreference
          
           option [@default None]
        
        
        ; [@key "consistency"]
      contextual_tuples: Contextual_tuple_keys.t
          
           option [@default None]
        
        
        ; [@key "contextual_tuples"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuple_key : Expand_request_tuple_key.t) : t = {
    tuple_key = tuple_key;
    authorization_model_id = None;
    consistency = None;
    contextual_tuples = None;
}

    

