(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Fga_object.t : Object represents an OpenFGA Object.  An Object is composed of a type and identifier (e.g. 'document:1')  See https://openfga.dev/docs/concepts#what-is-an-object
 *)



    
        type t = {
      _type: string
          
          
        
        
        ; [@key "type"]
      id: string
          
          
        
        
        ; [@key "id"]
} [@@deriving yojson { strict = false }, show, eq ];;

(** Object represents an OpenFGA Object.  An Object is composed of a type and identifier (e.g. 'document:1')  See https://openfga.dev/docs/concepts#what-is-an-object *)
let create (_type : string) (id : string) : t = {
    _type = _type;
    id = id;
}

    

