(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Leaf.t : A leaf node contains either - a set of users (which may be individual users, or usersets   referencing other relations) - a computed node, which is the result of a computed userset   value in the authorization model - a tupleToUserset nodes, containing the result of expanding   a tupleToUserset value in a authorization model.
 *)



    
        type t = {
      users: Users.t
          
           option [@default None]
        
        
        ; [@key "users"]
      computed: Computed.t
          
           option [@default None]
        
        
        ; [@key "computed"]
      tuple_to_userset: Userset_tree_tuple_to_userset.t
          
           option [@default None]
        
        
        ; [@key "tupleToUserset"]
} [@@deriving yojson { strict = false }, show, eq ];;

(** A leaf node contains either - a set of users (which may be individual users, or usersets   referencing other relations) - a computed node, which is the result of a computed userset   value in the authorization model - a tupleToUserset nodes, containing the result of expanding   a tupleToUserset value in a authorization model. *)
let create () : t = {
    users = None;
    computed = None;
    tuple_to_userset = None;
}

    

