(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      objects: string list
        
        
        ; [@key "objects"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (objects : string list) : t = {
    objects = objects;
}

    

