(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      users: User.t list
        
        
        ; [@key "users"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (users : User.t list) : t = {
    users = users;
}

    

