(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      stores: Store.t list
        
        
        ; [@key "stores"]
      continuation_token: string
          
          
        
        
        ; [@key "continuation_token"]
    (** The continuation token will be empty if there are no more stores. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (stores : Store.t list) (continuation_token : string) : t = {
    stores = stores;
    continuation_token = continuation_token;
}

    

