(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      authorization_model_id: string
          
           option [@default None]
        
        
        ; [@key "authorization_model_id"]
      _type: string
          
          
        
        
        ; [@key "type"]
      relation: string
          
          
        
        
        ; [@key "relation"]
      user: string
          
          
        
        
        ; [@key "user"]
      contextual_tuples: Contextual_tuple_keys.t
          
           option [@default None]
        
        
        ; [@key "contextual_tuples"]
      context: Yojson.Safe.t
          
           option [@default None]
        
        
        ; [@key "context"]
    (** Additional request context that will be used to evaluate any ABAC conditions encountered in the query evaluation. *)
      consistency: Enums.consistencypreference
          
           option [@default None]
        
        
        ; [@key "consistency"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (_type : string) (relation : string) (user : string) : t = {
    authorization_model_id = None;
    _type = _type;
    relation = relation;
    user = user;
    contextual_tuples = None;
    context = None;
    consistency = None;
}

    

