(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      authorization_model_id: string
          
           option [@default None]
        
        
        ; [@key "authorization_model_id"]
      _object: Fga_object.t
          
          
        
        
        ; [@key "object"]
      relation: string
          
          
        
        
        ; [@key "relation"]
      user_filters: User_type_filter.t list
        
        
        ; [@key "user_filters"]
    (** The type of results returned. Only accepts exactly one value. *)
      contextual_tuples: Tuple_key.t list
         [@default []]
        
        ; [@key "contextual_tuples"]
      context: Yojson.Safe.t
          
           option [@default None]
        
        
        ; [@key "context"]
    (** Additional request context that will be used to evaluate any ABAC conditions encountered in the query evaluation. *)
      consistency: Enums.consistencypreference
          
           option [@default None]
        
        
        ; [@key "consistency"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (_object : Fga_object.t) (relation : string) (user_filters : User_type_filter.t list) : t = {
    authorization_model_id = None;
    _object = _object;
    relation = relation;
    user_filters = user_filters;
    contextual_tuples = [];
    context = None;
    consistency = None;
}

    

