(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      relations: (string * Relation_metadata.t) list
        
         [@default []] [@to_yojson JsonSupport.of_map_of [%to_yojson: Relation_metadata.t]] [@of_yojson JsonSupport.to_map_of [%of_yojson: Relation_metadata.t]]
        ; [@key "relations"]
      _module: string
          
           option [@default None]
        
        
        ; [@key "module"]
      source_info: Source_info.t
          
           option [@default None]
        
        
        ; [@key "source_info"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    relations = [];
    _module = None;
    source_info = None;
}

    

