(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      nodes: Node.t list
        
        
        ; [@key "nodes"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (nodes : Node.t list) : t = {
    nodes = nodes;
}

    

