(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      name: string
          
          
        
        
        ; [@key "name"]
      leaf: Leaf.t
          
           option [@default None]
        
        
        ; [@key "leaf"]
      difference: Userset_tree_difference.t
          
           option [@default None]
        
        
        ; [@key "difference"]
      union: Nodes.t
          
           option [@default None]
        
        
        ; [@key "union"]
      intersection: Nodes.t
          
           option [@default None]
        
        
        ; [@key "intersection"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (name : string) : t = {
    name = name;
    leaf = None;
    difference = None;
    union = None;
    intersection = None;
}

    

