(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      user: string
          
           option [@default None]
        
        
        ; [@key "user"]
      relation: string
          
           option [@default None]
        
        
        ; [@key "relation"]
      _object: string
          
           option [@default None]
        
        
        ; [@key "object"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    user = None;
    relation = None;
    _object = None;
}

    

