(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      changes: Tuple_change.t list
        
        
        ; [@key "changes"]
      continuation_token: string
          
           option [@default None]
        
        
        ; [@key "continuation_token"]
    (** The continuation token will be identical if there are no new changes. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (changes : Tuple_change.t list) : t = {
    changes = changes;
    continuation_token = None;
}

    

