(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      authorization_models: Authorization_model.t list
        
        
        ; [@key "authorization_models"]
      continuation_token: string
          
           option [@default None]
        
        
        ; [@key "continuation_token"]
    (** The continuation token will be empty if there are no more models. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (authorization_models : Authorization_model.t list) : t = {
    authorization_models = authorization_models;
    continuation_token = None;
}

    

