(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      authorization_model: Authorization_model.t
          
           option [@default None]
        
        
        ; [@key "authorization_model"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    authorization_model = None;
}

    

