(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuples: Tuple.t list
        
        
        ; [@key "tuples"]
      continuation_token: string
          
          
        
        
        ; [@key "continuation_token"]
    (** The continuation token will be empty if there are no more tuples. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuples : Tuple.t list) (continuation_token : string) : t = {
    tuples = tuples;
    continuation_token = continuation_token;
}

    

