(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_key: Read_request_tuple_key.t
          
           option [@default None]
        
        
        ; [@key "tuple_key"]
      page_size: int32
          
           option [@default None]
        
        
        ; [@key "page_size"]
      continuation_token: string
          
           option [@default None]
        
        
        ; [@key "continuation_token"]
      consistency: Enums.consistencypreference
          
           option [@default None]
        
        
        ; [@key "consistency"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    tuple_key = None;
    page_size = None;
    continuation_token = None;
    consistency = None;
}

    

