(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Relation_reference.t : RelationReference represents a relation of a particular object type (e.g. 'document#viewer').
 *)



    
        type t = {
      _type: string
          
          
        
        
        ; [@key "type"]
      relation: string
          
           option [@default None]
        
        
        ; [@key "relation"]
      wildcard: Yojson.Safe.t
          
           option [@default None]
        
        
        ; [@key "wildcard"]
      condition: string
          
           option [@default None]
        
        
        ; [@key "condition"]
    (** The name of a condition that is enforced over the allowed relation. *)
} [@@deriving yojson { strict = false }, show, eq ];;

(** RelationReference represents a relation of a particular object type (e.g. 'document#viewer'). *)
let create (_type : string) : t = {
    _type = _type;
    relation = None;
    wildcard = None;
    condition = None;
}

    

