(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      directly_related_user_types: Relation_reference.t list
         [@default []]
        
        ; [@key "directly_related_user_types"]
      _module: string
          
           option [@default None]
        
        
        ; [@key "module"]
      source_info: Source_info.t
          
           option [@default None]
        
        
        ; [@key "source_info"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    directly_related_user_types = [];
    _module = None;
    source_info = None;
}

    

