(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      name: string
          
          
        
        
        ; [@key "name"]
    (** A reference (by name) of the relationship condition defined in the authorization model. *)
      context: Yojson.Safe.t
          
           option [@default None]
        
        
        ; [@key "context"]
    (** Additional context/data to persist along with the condition. The keys must match the parameters defined by the condition, and the value types must match the parameter type definitions. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (name : string) : t = {
    name = name;
    context = None;
}

    

