(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      file: string
          
           option [@default None]
        
        
        ; [@key "file"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    file = None;
}

    

