(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      code: int32
          
           option [@default None]
        
        
        ; [@key "code"]
      message: string
          
           option [@default None]
        
        
        ; [@key "message"]
      details: Any.t list
         [@default []]
        
        ; [@key "details"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    code = None;
    message = None;
    details = [];
}

    

