(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      key: Tuple_key.t
          
          
        
        
        ; [@key "key"]
      timestamp: string
          
          
        
        
        ; [@key "timestamp"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (key : Tuple_key.t) (timestamp : string) : t = {
    key = key;
    timestamp = timestamp;
}

    

