(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tupleset: Object_relation.t
          
          
        
        
        ; [@key "tupleset"]
      computed_userset: Object_relation.t
          
          
        
        
        ; [@key "computedUserset"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tupleset : Object_relation.t) (computed_userset : Object_relation.t) : t = {
    tupleset = tupleset;
    computed_userset = computed_userset;
}

    

