(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      user: string
          
          
        
        
        ; [@key "user"]
      relation: string
          
          
        
        
        ; [@key "relation"]
      _object: string
          
          
        
        
        ; [@key "object"]
      condition: Relationship_condition.t
          
           option [@default None]
        
        
        ; [@key "condition"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (user : string) (relation : string) (_object : string) : t = {
    user = user;
    relation = relation;
    _object = _object;
    condition = None;
}

    

