(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_key: Tuple_key.t
          
          
        
        
        ; [@key "tuple_key"]
      operation: Enums.tupleoperation
          
          
        
        
        ; [@key "operation"]
      timestamp: string
          
          
        
        
        ; [@key "timestamp"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuple_key : Tuple_key.t) (operation : Enums.tupleoperation) (timestamp : string) : t = {
    tuple_key = tuple_key;
    operation = operation;
    timestamp = timestamp;
}

    

