(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      _type: string
          
          
        
        
        ; [@key "type"]
      relations: (string * Userset.t) list
        
         [@default []] [@to_yojson JsonSupport.of_map_of [%to_yojson: Userset.t]] [@of_yojson JsonSupport.to_map_of [%of_yojson: Userset.t]]
        ; [@key "relations"]
      metadata: Metadata.t
          
           option [@default None]
        
        
        ; [@key "metadata"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (_type : string) : t = {
    _type = _type;
    relations = [];
    metadata = None;
}

    

