(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Typed_wildcard.t : Type bound public access.  Normally represented using the `<type>:*` syntax  `employee:*` represents every object of type `employee`, including those not currently present in the system  See https://openfga.dev/docs/concepts#what-is-type-bound-public-access
 *)



    
        type t = {
      _type: string
          
          
        
        
        ; [@key "type"]
} [@@deriving yojson { strict = false }, show, eq ];;

(** Type bound public access.  Normally represented using the `<type>:*` syntax  `employee:*` represents every object of type `employee`, including those not currently present in the system  See https://openfga.dev/docs/concepts#what-is-type-bound-public-access *)
let create (_type : string) : t = {
    _type = _type;
}

    

