(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      users: string list
        
        
        ; [@key "users"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (users : string list) : t = {
    users = users;
}

    

