(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      this: Yojson.Safe.t
          
           option [@default None]
        
        
        ; [@key "this"]
    (** A DirectUserset is a sentinel message for referencing the direct members specified by an object/relation mapping. *)
      computed_userset: Object_relation.t
          
           option [@default None]
        
        
        ; [@key "computedUserset"]
      tuple_to_userset: Tuple_to_userset.t
          
           option [@default None]
        
        
        ; [@key "tupleToUserset"]
      union: Usersets.t
          
           option [@default None]
        
        
        ; [@key "union"]
      intersection: Usersets.t
          
           option [@default None]
        
        
        ; [@key "intersection"]
      difference: Difference.t
          
           option [@default None]
        
        
        ; [@key "difference"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    this = None;
    computed_userset = None;
    tuple_to_userset = None;
    union = None;
    intersection = None;
    difference = None;
}

    

