(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tupleset: string
          
          
        
        
        ; [@key "tupleset"]
      computed: Computed.t list
        
        
        ; [@key "computed"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tupleset : string) (computed : Computed.t list) : t = {
    tupleset = tupleset;
    computed = computed;
}

    

