(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      child: Userset.t list
        
        
        ; [@key "child"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (child : Userset.t list) : t = {
    child = child;
}

    

