(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Userset_tree.t : A UsersetTree contains the result of an Expansion.
 *)



    
        type t = {
      root: Node.t
          
           option [@default None]
        
        
        ; [@key "root"]
} [@@deriving yojson { strict = false }, show, eq ];;

(** A UsersetTree contains the result of an Expansion. *)
let create () : t = {
    root = None;
}

    

