(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema User.t : User.  Represents any possible value for a user (subject or principal). Can be a: - Specific user object e.g.: 'user:will', 'folder:marketing', 'org:contoso', ...) - Specific userset (e.g. 'group:engineering#member') - Public-typed wildcard (e.g. 'user:*')  See https://openfga.dev/docs/concepts#what-is-a-user
 *)



    
        type t = {
      _object: Fga_object.t
          
           option [@default None]
        
        
        ; [@key "object"]
      userset: Userset_user.t
          
           option [@default None]
        
        
        ; [@key "userset"]
      wildcard: Typed_wildcard.t
          
           option [@default None]
        
        
        ; [@key "wildcard"]
} [@@deriving yojson { strict = false }, show, eq ];;

(** User.  Represents any possible value for a user (subject or principal). Can be a: - Specific user object e.g.: 'user:will', 'folder:marketing', 'org:contoso', ...) - Specific userset (e.g. 'group:engineering#member') - Public-typed wildcard (e.g. 'user:*')  See https://openfga.dev/docs/concepts#what-is-a-user *)
let create () : t = {
    _object = None;
    userset = None;
    wildcard = None;
}

    

