(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      base: Node.t
          
          
        
        
        ; [@key "base"]
      subtract: Node.t
          
          
        
        
        ; [@key "subtract"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (base : Node.t) (subtract : Node.t) : t = {
    base = base;
    subtract = subtract;
}

    

