(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      _type: string
          
          
        
        
        ; [@key "type"]
      relation: string
          
           option [@default None]
        
        
        ; [@key "relation"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (_type : string) : t = {
    _type = _type;
    relation = None;
}

    

