(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Userset_user.t : Userset.  A set or group of users, represented in the `<type>:<id>#<relation>` format  `group:fga#member` represents all members of group FGA, not to be confused by `group:fga` which represents the group itself as a specific object.  See: https://openfga.dev/docs/modeling/building-blocks/usersets#what-is-a-userset
 *)



    
        type t = {
      _type: string
          
          
        
        
        ; [@key "type"]
      id: string
          
          
        
        
        ; [@key "id"]
      relation: string
          
          
        
        
        ; [@key "relation"]
} [@@deriving yojson { strict = false }, show, eq ];;

(** Userset.  A set or group of users, represented in the `<type>:<id>#<relation>` format  `group:fga#member` represents all members of group FGA, not to be confused by `group:fga` which represents the group itself as a specific object.  See: https://openfga.dev/docs/modeling/building-blocks/usersets#what-is-a-userset *)
let create (_type : string) (id : string) (relation : string) : t = {
    _type = _type;
    id = id;
    relation = relation;
}

    

