(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      assertions: Assertion.t list
        
        
        ; [@key "assertions"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (assertions : Assertion.t list) : t = {
    assertions = assertions;
}

    

