(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      authorization_model_id: string
          
          
        
        
        ; [@key "authorization_model_id"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (authorization_model_id : string) : t = {
    authorization_model_id = authorization_model_id;
}

    

