(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_keys: Tuple_key.t list
        
        
        ; [@key "tuple_keys"]
      on_duplicate: Enums.on_missing
           option [@default
            Some(`Error)
            
          ]
        ; [@key "on_duplicate"]
    (** On 'error' ( or unspecified ), the API returns an error if an identical tuple already exists. On 'ignore', identical writes are treated as no-ops (matching on user, relation, object, and RelationshipCondition). *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuple_keys : Tuple_key.t list) : t = {
    tuple_keys = tuple_keys;
    on_duplicate = None;
}

    

