(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      writes: Write_request_writes.t
          
           option [@default None]
        
        
        ; [@key "writes"]
      deletes: Write_request_deletes.t
          
           option [@default None]
        
        
        ; [@key "deletes"]
      authorization_model_id: string
          
           option [@default None]
        
        
        ; [@key "authorization_model_id"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    writes = None;
    deletes = None;
    authorization_model_id = None;
}

    

