(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      tuple_keys: Tuple_key_without_condition.t list
        
        
        ; [@key "tuple_keys"]
      on_missing: Enums.on_missing
           option [@default
            Some(`Error)
            
          ]
        ; [@key "on_missing"]
    (** On 'error', the API returns an error when deleting a tuple that does not exist. On 'ignore', deletes of non-existent tuples are treated as no-ops. *)
} [@@deriving yojson { strict = false }, show, eq ];;

let create (tuple_keys : Tuple_key_without_condition.t list) : t = {
    tuple_keys = tuple_keys;
    on_missing = None;
}

    

