(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)



    
        type t = {
      type_definitions: Type_definition.t list
        
        
        ; [@key "type_definitions"]
      schema_version: string
          
          
        
        
        ; [@key "schema_version"]
      conditions: (string * Condition.t) list
        
         [@default []] [@to_yojson JsonSupport.of_map_of [%to_yojson: Condition.t]] [@of_yojson JsonSupport.to_map_of [%of_yojson: Condition.t]]
        ; [@key "conditions"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create (type_definitions : Type_definition.t list) (schema_version : string) : t = {
    type_definitions = type_definitions;
    schema_version = schema_version;
    conditions = [];
}

    

